apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: translatecontroller
    visualize: "true"
  name: translatecontroller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: translateservicepod
        visualize: "true"
    spec:
      containers:
      - image: gcr.io/kubernetestests/translateservice:01
        name: translate
        ports:
        - name: translate
          containerPort: 9090
          hostPort: 9090

