apiVersion: v1
kind: Service
metadata:
  labels:
    name: translateservice
    visualize: "true"
  name: translateservice
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 9090
      name: translateservice
  selector:
    name: translateservicepod
