apiVersion: v1
kind: Pod
metadata:
  name: jee-app
  labels:
    app: webapplication
    name: web-pod
spec:
  containers:
    - name: app-server
      image: jboss/wildfly
      ports:
        - containerPort: 8080
    - name: database
      image: mongo
      ports:
        - containerPort: 27017
