apiVersion: v1
kind: Service
metadata:
  labels:
    name: faceservice
    visualize: "true"
  name: faceservice
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 9090
      name: faceservice
  selector:
    name: faceservicepod
