apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: sdbcontroller
    visualize: "true"
  name: sdbcontroller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: sdbpod
        visualize: "true"
    spec:
      containers:
      - image: gcr.io/kubernetestests/simpleservicewithdb:01
        name: sdb
        ports:
        - name: sdb
          containerPort: 8080
          hostPort: 8080

