apiVersion: v1
kind: Service
metadata:
  labels:
    name: sdbservice
    visualize: "true"
  name: sdbservice
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      name: sdb
  selector:
    name: sdbpod
