apiVersion: v1
kind: Service
metadata:
  labels:
    name: simpleservice
    visualize: "true"
  name: simpleservice
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 9090
      name: simpleservice
  selector:
    name: simpleservicepod
